// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImputData struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int64    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImputData) Reset()         { *m = ImputData{} }
func (m *ImputData) String() string { return proto.CompactTextString(m) }
func (*ImputData) ProtoMessage()    {}
func (*ImputData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *ImputData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImputData.Unmarshal(m, b)
}
func (m *ImputData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImputData.Marshal(b, m, deterministic)
}
func (m *ImputData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImputData.Merge(m, src)
}
func (m *ImputData) XXX_Size() int {
	return xxx_messageInfo_ImputData.Size(m)
}
func (m *ImputData) XXX_DiscardUnknown() {
	xxx_messageInfo_ImputData.DiscardUnknown(m)
}

var xxx_messageInfo_ImputData proto.InternalMessageInfo

func (m *ImputData) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *ImputData) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *ImputData) GetC() int64 {
	if m != nil {
		return m.C
	}
	return 0
}

type OutputData struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int64    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	Result               string   `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputData) Reset()         { *m = OutputData{} }
func (m *OutputData) String() string { return proto.CompactTextString(m) }
func (*OutputData) ProtoMessage()    {}
func (*OutputData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *OutputData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputData.Unmarshal(m, b)
}
func (m *OutputData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputData.Marshal(b, m, deterministic)
}
func (m *OutputData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputData.Merge(m, src)
}
func (m *OutputData) XXX_Size() int {
	return xxx_messageInfo_OutputData.Size(m)
}
func (m *OutputData) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputData.DiscardUnknown(m)
}

var xxx_messageInfo_OutputData proto.InternalMessageInfo

func (m *OutputData) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *OutputData) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *OutputData) GetC() int64 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *OutputData) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ImputData)(nil), "main.ImputData")
	proto.RegisterType((*OutputData)(nil), "main.OutputData")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x32,
	0xe5, 0xe2, 0xf4, 0xcc, 0x2d, 0x28, 0x2d, 0x71, 0x49, 0x2c, 0x49, 0x14, 0xe2, 0xe1, 0x62, 0x4c,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0x04, 0xf3, 0x92, 0x24, 0x98, 0x20, 0xbc, 0x24,
	0x10, 0x2f, 0x59, 0x82, 0x19, 0xc2, 0x4b, 0x56, 0xf2, 0xe3, 0xe2, 0xf2, 0x2f, 0x2d, 0x21, 0x59,
	0x9f, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x04, 0x8b, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x94, 0x97, 0xc4, 0x06, 0x76, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x10,
	0x17, 0x3a, 0xa3, 0x00, 0x00, 0x00,
}
